language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zhufengnodejs"
  - git config user.email "zhufengnodejs@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://317b2b994cc3f6c88d45ddfcd4727393047e564e@github.com/zhufengnodejs/zhufengnodejs.github.io.git" master:master


branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/zhufengnodejs/zhufengnodejs.github.io.git